name: Carpentry
on:
  pull_request:
env:
  IMAGE_NAME: arcaflow-plugin-uperf
  IMAGE_TAG: ${{ github.ref_name }}
  GITHUB_USERNAME: ${{ github.actor }}
  GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_NAMESPACE: ${{ github.repository_owner }}
  QUAY_NAMESPACE: ${{ secrets.QUAY_NAMESPACE }}
  QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
  QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
jobs:
  carpenter-build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: set_image_tag
        run: |
          echo ${{ github.sha }} > $commit_hash
          echo "${{ github.ref_name }}-${commit_hash:0:7}" > $IMAGE_TAG
      - name: show image tag
        run: echo $IMAGE_TAG
      - name: Checkout this project
        uses: actions/checkout@v3
      - name: carpenter build
        uses: arcalot/arcaflow-plugin-image-builder@main
        with:
          args: build --build
